baseURL = 'https://oscarvantol.nl/'
languageCode = 'en-us'
title = 'oscarvantol.nl'
theme = 'PaperMod'
relativeUrl = true

[params.homeInfoParams]
title = "Hey there 👋🏻"
content = "I'm Oscar - a father of 4 that loves technology since I can remember, I've written my first code in the 90s and never stopped. As a developer with a passion for networks/infrastructure and hardware I got excited about the potential of Microsoft Azure early on. You can find me talking about PaaS and Serverless at conferences, on blogs or youtube whenever there is time. I am working as a Principal Cloud Architect at Betabit in The Netherland, helping out customers by architecting scalable, multi tenant, secure software. Next to that I coach teams and their organisations to become more agile in the way they design, discuss, develop and release their software."


[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/oscarvantol"

[[params.socialIcons]]
name = "github"
url = "https://github.com/oscarvantol"

[[params.socialIcons]]
name = "dev"
url = "https://dev.to/oscarvantol/"

[[params.socialIcons]]
name = "linkedin"
url = "https://www.linkedin.com/in/oscar-van-tol/"




[menu]
[[menu.main]]
  identifier = 'home'
  name = 'Home'
  title = 'home'
  url = '/'  
  weight = 1
[[menu.main]]
  identifier = 'blogs'
  name = 'Blogs'
  title = 'blogs'
  url = '/blogs/'
  weight = 2  
[[menu.main]]
  identifier = 'videos'
  name = 'Videos'
  title = 'videos'
  url = '/videos/'
  weight = 3
[[menu.main]]
  identifier = 'podcast'
  name = 'Podcast'
  title = 'podcast'
  url = '/podcast/'
  weight = 4

